[package]
edition    = "2021"
license    = "MIT"
name       = "bindings"
repository = "https://github.com/pmqueiroz/nephrit.git"
version    = "0.1.0"

[dependencies]
napi        = "3.0.0"
napi-derive = "3.0.0"
serde       = { version = "1.0.228", features = ["derive"] }
serde_json  = "1.0.145"
