[package]
edition    = "2021"
license    = "MIT"
name       = "utils"
repository = "https://github.com/pmqueiroz/nephrit.git"
version    = "0.1.0"

[dependencies]
globwalk   = "0.9.1"
serde      = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
